# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  mountpoint:
    description: Location to mount share on machine.
    type: string
  noexec:
    default: false
    description: Block execution of binaries on NFS share.
    type: boolean
  nosuid:
    default: false
    description: Do not honour suid and sgid bits on NFS share.
    type: boolean
  nodev:
    default: false
    description: Blocking interpretation of character or block devices on NFS share.
    type: boolean
  read-only:
    default: false
    description: Mount NFS shares as read-only.
    type: boolean